title: "The Letters of Theano: Neopythagorean Pseudoepigrapha" # You will insert your title here.
email: smaya.anand@gmail.com
description: by Smaya Anand, Hannah Hedrick, Frances O'Neil # Author names go here.

baseurl: "/pythagorean" # the subpath of your site. Change it if the name of your repository is other than "mindoc"

twitter_username: jekyllrb
github_username:  jekyll

# Build settings

plugins:
  - jekyll-feed

collections:
  mindoc_media:
    output: true
    layout: 'image_description'
